# Generated by Django 3.1.2 on 2020-11-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24)),
                ('content', models.CharField(max_length=400)),
                ('closing_data', models.DateField()),
                ('writer', models.CharField(max_length=10)),
                ('personnel', models.CharField(max_length=100)),
                ('hashtag', models.CharField(max_length=100, null=True)),
                ('profile', models.ImageField(max_length=200, upload_to='')),
            ],
        ),
    ]
