# Generated by Django 3.1.2 on 2020-11-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='profile',
            field=models.CharField(max_length=200),
        ),
    ]
