# Generated by Django 3.1.2 on 2020-11-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_project_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='writer',
            field=models.CharField(max_length=100),
        ),
    ]
