# Generated by Django 3.1.2 on 2020-11-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='participation',
            table='participation',
        ),
    ]
