# Generated by Django 3.1.2 on 2020-11-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0002_auto_20201124_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='student_area',
            field=models.CharField(max_length=20),
        ),
    ]
