# Generated by Django 3.1.2 on 2020-11-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=12)),
                ('birthday', models.DateField()),
                ('school', models.CharField(max_length=4)),
                ('profile', models.CharField(max_length=128)),
                ('github', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=11)),
                ('area', models.CharField(max_length=24)),
                ('hashtag', models.CharField(max_length=40)),
            ],
        ),
    ]
